--										Alexamara Marina Group Analysis In SSMS

-- Load The Data Included In the "Database Creation For Analysis In SSMS" File Before Running The Below Commands.

-- Setting Database To Use
USE GUIDE;

-- Format For All Alexamara Marina Group Tables
EXEC SP_COLUMNS MARINA;
EXEC SP_COLUMNS OWNER;
EXEC SP_COLUMNS MARINA_SLIP;
EXEC SP_COLUMNS SERVICE_CATEGORY;
EXEC SP_COLUMNS SERVICE_REQUEST;

-- Viewing All Alexamara Marina Group Tables
SELECT MARINA_NUM, NAME, ADDRESS, CITY, STATE, ZIP
FROM MARINA;

SELECT OWNER_NUM, LAST_NAME, FIRST_NAME, ADDRESS, CITY, STATE, ZIP
FROM OWNER;

SELECT SLIP_ID, MARINA_NUM, SLIP_NUM, LENGTH, FORMAT(RENTAL_FEE, 'C') AS RENTAL_FEE, BOAT_NAME, BOAT_TYPE, OWNER_NUM 
FROM MARINA_SLIP;

SELECT CATEGORY_NUM, CATEGORY_DESCRIPTION
FROM SERVICE_CATEGORY;

SELECT SERVICE_ID, SLIP_ID, CATEGORY_NUM, DESCRIPTION, STATUS, EST_HOURS, SPENT_HOURS, NEXT_SERVICE_DATE
FROM SERVICE_REQUEST;

-- Owners Of All Boats
SELECT OWNER_NUM, LAST_NAME, FIRST_NAME
FROM OWNER;

-- All Owners That Live In "Rivard"
SELECT LAST_NAME, FIRST_NAME, CITY
FROM OWNER
WHERE CITY = 'Rivard';

-- All Owners That Do Not Live In "Rivard"
SELECT LAST_NAME, FIRST_NAME, CITY
FROM OWNER
WHERE CITY != 'Rivard';

-- All Boats That Are 30 Feet Or Less In Length
SELECT MARINA_NUM, SLIP_NUM, LENGTH	
FROM MARINA_SLIP
WHERE LENGTH <= 30;

-- All Boats With Type "Ray 4025"
SELECT SLIP_NUM, BOAT_TYPE
FROM MARINA_SLIP
WHERE BOAT_TYPE = 'Ray 4025';

-- All Boats With Type "Ray 4025" In "Marina 1"
SELECT SLIP_NUM, BOAT_TYPE, MARINA_NUM
FROM MARINA_SLIP
WHERE BOAT_TYPE = 'Ray 4025' AND MARINA_NUM = '1';

-- All Boats Between 25 and 30 In Length
SELECT BOAT_NAME, LENGTH
FROM MARINA_SLIP
WHERE LENGTH BETWEEN 25 AND 30

-- All Boats With A Rental Fee Less Than $3,000 In "Marina 1"
SELECT SLIP_ID, BOAT_NAME, RENTAL_FEE
FROM MARINA_SLIP
WHERE MARINA_NUM = 1 AND RENTAL_FEE < 3000;

-- Estimated Labor Cost For All Service Requests
SELECT SLIP_ID, CATEGORY_NUM, EST_HOURS, EST_HOURS * 60 AS LABOR_COST
FROM SERVICE_REQUEST;

-- All "Sprite 3000", "Sprite 4000", and "Ray 4025" Boats
SELECT MARINA_NUM, SLIP_NUM, BOAT_TYPE, BOAT_NAME
FROM MARINA_SLIP
WHERE BOAT_TYPE IN ('Sprite 400', 'Sprite 3000', 'Ray 4025')

-- All Boats Ordered By Marina And Name
SELECT MARINA_NUM, SLIP_NUM, BOAT_NAME
FROM MARINA_SLIP
ORDER BY MARINA_NUM, BOAT_NAME;

-- Total "Dolphin 28" Boats
SELECT COUNT(*) AS TOTAL
FROM MARINA_SLIP
WHERE BOAT_TYPE = 'Dolphin 28';