---- Creating Tables
CREATE TABLE PETSTORE (
    ID INTEGER NOT NULL,
    PET CHAR(25),
    SALEPRICE DECIMAL(6,2),
    PROFIT DECIMAL(6,2),
    SALEDATE DATE
    );

CREATE TABLE PET (
    ID INTEGER NOT NULL,
    ANIMAL VARCHAR(25),
    QUANTITY INTEGER
    );

---- Adding Values To Tables
INSERT INTO PETSTORE VALUES
    (1,'Cat',450.09,100.47,'2018-05-29'),
    (2,'Dog',666.66,150.76,'2018-06-01'),
    (3,'Parrot',50.00,8.9,'2018-06-04'),
    (4,'Hamster',60.60,12,'2018-06-11'),
    (5,'Goldfish',48.48,3.5,'2018-06-14');
    
INSERT INTO PET VALUES
    (1,'Cat',3),
    (2,'Dog',4),
    (3,'Hamster',2);

---- Adding A New A Column To A Table
ALTER TABLE PETSTORE
ADD QUANTITY INTEGER;

UPDATE PETSTORE 
	SET QUANTITY = 9 
	WHERE ID = 1;
UPDATE PETSTORE 
	SET QUANTITY = 3 
	WHERE ID = 2;
UPDATE PETSTORE 
	SET QUANTITY = 2 
	WHERE ID = 3;
UPDATE PETSTORE 
	SET QUANTITY = 6 
	WHERE ID = 4;
UPDATE PETSTORE 
	SET QUANTITY = 24 
	WHERE ID = 5;

---- Removing A Column From A Table
ALTER TABLE PETSTORE
DROP COLUMN PROFIT;

---- Updating Column Formating
ALTER TABLE PETSTORE 
ALTER COLUMN PET VARCHAR(20);

ALTER TABLE PET
ALTER COLUMN ANIMAL VARCHAR(20);

---- Viewing Tables
SELECT * FROM PET;
SELECT * FROM PETSTORE;

---- Clearing Data From Tables
TRUNCATE TABLE PET;
TRUNCATE TABLE PETSTORE;

SELECT * FROM PET;
SELECT * FROM PETSTORE;

---- Deleting Tables
DROP TABLE PET;
DROP TABLE PETSTORE;

SELECT * FROM PET;
SELECT * FROM PETSTORE;