--												Henry Books Analysis In SSMS

-- Load The Data Included In the "Database Creation For Analysis In SSMS" File Before Running The Below Commands.

-- Setting Database To Use
USE GUIDE;

-- Format For All Henry Books Tables 
EXEC SP_COLUMNS BRANCH;
EXEC SP_COLUMNS PUBLISHER;
EXEC SP_COLUMNS AUTHOR;
EXEC SP_COLUMNS BOOK;
EXEC SP_COLUMNS WROTE;
EXEC SP_COLUMNS INVENTORY;

-- Viewing All Henry Books Tables
SELECT BRANCH_NUM, BRANCH_NAME, BRANCH_LOCATION, NUM_EMPLOYEES 
FROM BRANCH;

SELECT PUBLISHER_CODE, PUBLISHER_NAME, CITY 
FROM PUBLISHER;

SELECT AUTHOR_NUM, AUTHOR_LAST, AUTHOR_FIRST 
FROM AUTHOR;

SELECT BOOK_CODE, AUTHOR_NUM, SEQUENCE 
FROM WROTE;

SELECT BOOK_CODE, BRANCH_NUM, ON_HAND 
FROM INVENTORY;

SELECT BOOK_CODE, TITLE, PUBLISHER_CODE, TYPE, FORMAT(PRICE, 'C') AS PRICE, PAPERBACK 
FROM BOOK;

-- Book Codes And Titles For All Books
SELECT BOOK_CODE, TITLE 
FROM BOOK;

-- All Publishers Located In Boston
SELECT PUBLISHER_NAME 
FROM PUBLISHER 
WHERE CITY = 'Boston';

-- All Publishers Not Located In New York
SELECT PUBLISHER_NAME 
FROM PUBLISHER 
WHERE CITY != 'New York';

-- Each Branch With At Least 9 Employees
SELECT BRANCH_NAME 
FROM BRANCH 
WHERE NUM_EMPLOYEES <= 9;

-- All Books With Type HOR
SELECT BOOK_CODE, TITLE, TYPE 
FROM BOOK 
WHERE TYPE = 'HOR';

-- All Paperback Books With Type HOR
SELECT BOOK_CODE, TITLE, TYPE 
FROM BOOK 
WHERE TYPE = 'HOR' AND PAPERBACK = 'Y';

-- All Books With Type HOR Or Published By SC
SELECT BOOK_CODE, TITLE, TYPE 
FROM BOOK 
WHERE TYPE = 'HOR' OR PUBLISHER_CODE = 'SC';

-- All Books With A Price Above 15 And Below 25
SELECT BOOK_CODE, TITLE, PRICE 
FROM BOOK 
WHERE PRICE BETWEEN 15 AND 25;

-- All Type "MYS" Books With A Price Less Than 20
SELECT BOOK_CODE, TITLE, TYPE, PRICE 
FROM BOOK 
WHERE TYPE = 'MYS' AND PRICE < 20;

-- Book Prices With A 10% Discount
SELECT BOOK_CODE, TITLE, (PRICE * .90) AS DISCOUNTED_PRICE 
FROM BOOK;

-- All Publishers With The Word "And" In Their Name
SELECT PUBLISHER_NAME 
FROM PUBLISHER 
WHERE PUBLISHER_NAME LIKE '% AND %';

-- All Type "SFI", "MYS", And "HOR" Books Listed Alphabetically
SELECT BOOK_CODE, TITLE, TYPE 
FROM BOOK 
WHERE TYPE IN ('SFI', 'MYS', 'HOR') 
ORDER BY TITLE;

-- The Price Of All Type "SFI", "MYS", And "HOR" Books Ordered By Price And Title
SELECT BOOK_CODE, TITLE, TYPE, PRICE 
FROM BOOK 
WHERE TYPE IN ('SFI', 'MYS', 'HOR') 
ORDER BY PRICE DESC, TITLE

-- The Distinct Type Of All Books
SELECT DISTINCT TYPE 
FROM BOOK;

-- Total Count Of All "SFI" Books
SELECT COUNT(*) AS TOTAL
FROM BOOK 
WHERE TYPE = 'SFI';

-- The Average Price Of All Types
SELECT TYPE, AVG(PRICE) AS AVG_PRICE 
FROM BOOK 
GROUP BY TYPE; 

-- The Average Price Of All Paperback Books By Type 
SELECT TYPE, AVG(PRICE) AS AVG_PRICE 
FROM BOOK 
WHERE PAPERBACK = 'Y' 
GROUP BY TYPE; 

-- The Average Price Of All Paperback Books By Type With A Higher Price Than 10
SELECT TYPE, AVG(PRICE) AS AVG_PRICE 
FROM BOOK 
WHERE PAPERBACK = 'Y' 
GROUP BY TYPE 
HAVING AVG(PRICE) > 10;

-- Most Expensive Books
SELECT TITLE, PRICE 
FROM BOOK 
WHERE PRICE = (SELECT MAX(PRICE) FROM BOOK);

-- Least Expensive Books
SELECT TITLE, PRICE 
FROM BOOK 
WHERE PRICE = (SELECT MIN(PRICE) FROM BOOK);

-- Total Employees In All Branches
SELECT SUM(NUM_EMPLOYEES) AS TOTAL_EMPLOYEES 
FROM BRANCH;

-- All Books Ordered By Publisher Name
SELECT BOOK_CODE, TITLE, P.PUBLISHER_CODE, PUBLISHER_NAME
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE
ORDER BY PUBLISHER_NAME;

-- All Books Published By "Scribner"
SELECT BOOK_CODE, TITLE, PRICE
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE AND P.PUBLISHER_NAME = 'Scribner';

-- All Books Published By "Scribner" Priced Greater Than 14
SELECT BOOK_CODE, TITLE, PRICE
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE AND P.PUBLISHER_NAME = 'Scribner' AND PRICE >= 14;

-- All Books In Stock In Branch 3
SELECT B.BOOK_CODE, TITLE, ON_HAND
FROM BOOK B, INVENTORY I
WHERE B.BOOK_CODE = I.BOOK_CODE AND BRANCH_NUM = 3;

-- All Books Published By "Berkley Publishing" With Type "PSY"
SELECT TITLE, TYPE, P.PUBLISHER_NAME
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE AND TYPE = 'PSY' AND P.PUBLISHER_NAME = 'Berkley Publishing';

-- All Books By "Author 18"
SELECT TITLE
FROM BOOK
WHERE BOOK_CODE IN (SELECT BOOK_CODE FROM WROTE WHERE AUTHOR_NUM = 18);

-- All Books By "Author 18" But Using Exists
SELECT TITLE
FROM BOOK
WHERE EXISTS (SELECT BOOK_CODE FROM WROTE W WHERE BOOK.BOOK_CODE = W.BOOK_CODE AND AUTHOR_NUM = 18);

-- Books By "Author 20" In Branch 2
SELECT BOOK_CODE, TITLE
FROM BOOK
WHERE BOOK_CODE IN 
(SELECT BOOK_CODE FROM WROTE WHERE AUTHOR_NUM = 20 AND BOOK_CODE IN (SELECT BOOK_CODE FROM INVENTORY WHERE BRANCH_NUM = 2));