--							Joins And Subqueries Using Alexamara Marina Group In SSMS

-- Load The Data Included In the "Database Creation For Analysis In SSMS" File Before Running The Below Commands.

-- Setting Database To Use
USE GUIDE;

-- Viewing All Alexamara Marina Group Tables
SELECT MARINA_NUM, NAME, ADDRESS, CITY, STATE, ZIP
FROM MARINA;

SELECT OWNER_NUM, LAST_NAME, FIRST_NAME, ADDRESS, CITY, STATE, ZIP
FROM OWNER;

SELECT SLIP_ID, MARINA_NUM, SLIP_NUM, LENGTH, FORMAT(RENTAL_FEE, 'C') AS RENTAL_FEE, BOAT_NAME, BOAT_TYPE, OWNER_NUM 
FROM MARINA_SLIP;

SELECT CATEGORY_NUM, CATEGORY_DESCRIPTION
FROM SERVICE_CATEGORY;

SELECT SERVICE_ID, SLIP_ID, CATEGORY_NUM, DESCRIPTION, STATUS, EST_HOURS, SPENT_HOURS, NEXT_SERVICE_DATE
FROM SERVICE_REQUEST;

-- All Boat Owners In The Marina
SELECT MARINA_NUM, SLIP_NUM, BOAT_NAME, S.OWNER_NUM, FIRST_NAME, LAST_NAME
FROM MARINA_SLIP S, OWNER O
WHERE S.OWNER_NUM = O.OWNER_NUM;

-- Determining Discounted Rent For All Owners
SELECT MARINA_NUM, SLIP_ID, SLIP_NUM, S.OWNER_NUM, O.LAST_NAME, RENTAL_FEE, (RENTAL_FEE * .9825) AS DISCOUNT 
FROM MARINA_SLIP S, OWNER O 
WHERE S.OWNER_NUM = O.OWNER_NUM;

-- All Open Or Completed Service Requests By Slip ID
SELECT SLIP_ID, DESCRIPTION, STATUS
FROM SERVICE_REQUEST;

-- All Maintenance Requests By Owner And Time Spent Versus Estimated
SELECT S.SLIP_ID, MARINA_NUM, SLIP_NUM, EST_HOURS, SPENT_HOURS, S.OWNER_NUM, O.LAST_NAME
FROM MARINA_SLIP S, SERVICE_REQUEST R, OWNER O
WHERE S.OWNER_NUM = O.OWNER_NUM AND R.SLIP_ID = S.SLIP_ID

-- All Owners With Boats In 30 Foot Slips
SELECT FIRST_NAME, LAST_NAME
FROM OWNER
WHERE OWNER_NUM IN (SELECT OWNER_NUM FROM MARINA_SLIP WHERE LENGTH = 30);

-- All Boats In Marina 1 By Owner
SELECT BOAT_NAME, O.OWNER_NUM, LAST_NAME, FIRST_NAME
FROM MARINA_SLIP S, OWNER O
WHERE S.OWNER_NUM = O.OWNER_NUM AND MARINA_NUM = 1

-- All Boats In Marina 1 By Owner And In 40 Foot Slips
SELECT BOAT_NAME, O.OWNER_NUM, LAST_NAME, FIRST_NAME
FROM MARINA_SLIP S, OWNER O
WHERE S.OWNER_NUM = O.OWNER_NUM AND MARINA_NUM = 1 AND LENGTH = 40;

-- All Sprite 4000 Boats Or By Owners That Live In Grander Bay
SELECT MARINA_NUM, SLIP_NUM, BOAT_NAME
FROM MARINA_SLIP
WHERE BOAT_TYPE = 'Sprite 4000' OR OWNER_NUM IN (SELECT OWNER_NUM FROM OWNER WHERE CITY = 'Grander Bay');

-- All Non-Sprite 4000 Boats Or By Owners That Live In Grander Bay
SELECT MARINA_NUM, SLIP_NUM, BOAT_NAME
FROM MARINA_SLIP
WHERE BOAT_TYPE != 'Sprite 4000' OR OWNER_NUM IN (SELECT OWNER_NUM FROM OWNER WHERE CITY = 'Grander Bay');

-- Service Requests Where The Estimated Hours Is Greater Than At Least One Category 3 Service
SELECT SERVICE_ID, SLIP_ID
FROM SERVICE_REQUEST
WHERE EST_HOURS > ANY (SELECT EST_HOURS FROM SERVICE_REQUEST WHERE CATEGORY_NUM = 3);

-- Service Requests Where The Estimated Hours Is Greater Than All Category 3 Services
SELECT SERVICE_ID, SLIP_ID
FROM SERVICE_REQUEST
WHERE EST_HOURS > ALL (SELECT EST_HOURS FROM SERVICE_REQUEST WHERE CATEGORY_NUM = 3);

-- All Category 2 Services Requests By Boat Name, Owner Number, Estimated Hours, And Spent Hours 
SELECT R.SLIP_ID, BOAT_NAME, OWNER_NUM, SERVICE_ID, EST_HOURS, SPENT_HOURS
FROM MARINA_SLIP S, SERVICE_REQUEST R
WHERE S.SLIP_ID = R.SLIP_ID AND CATEGORY_NUM = 2;

-- All Service Requests By Boat Name, Owner Number, Estimated Hours, And Spent Hours 
SELECT R.SLIP_ID, BOAT_NAME, OWNER_NUM, SERVICE_ID, EST_HOURS, SPENT_HOURS
FROM MARINA_SLIP S, SERVICE_REQUEST R
WHERE S.SLIP_ID = R.SLIP_ID;