--									Joins And Subqueries Using Henry Books In SSMS

-- Load The Data Included In the "Database Creation For Analysis In SSMS" File Before Running The Below Commands.

-- Setting Database To Use
USE GUIDE;

-- Viewing All Henry Books Tables
SELECT BRANCH_NUM, BRANCH_NAME, BRANCH_LOCATION, NUM_EMPLOYEES 
FROM BRANCH;

SELECT PUBLISHER_CODE, PUBLISHER_NAME, CITY 
FROM PUBLISHER;

SELECT AUTHOR_NUM, AUTHOR_LAST, AUTHOR_FIRST 
FROM AUTHOR;

SELECT BOOK_CODE, AUTHOR_NUM, SEQUENCE 
FROM WROTE;

SELECT BOOK_CODE, BRANCH_NUM, ON_HAND 
FROM INVENTORY;

SELECT BOOK_CODE, TITLE, PUBLISHER_CODE, TYPE, FORMAT(PRICE, 'C') AS PRICE, PAPERBACK 
FROM BOOK;

-- All Books Ordered By Publisher Name
SELECT BOOK_CODE, TITLE, P.PUBLISHER_CODE, PUBLISHER_NAME
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE
ORDER BY PUBLISHER_NAME;

-- All Books Published By "Scribner"
SELECT BOOK_CODE, TITLE, PRICE
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE AND P.PUBLISHER_NAME = 'Scribner';

-- All Books Published By "Scribner" Priced Greater Than 14
SELECT BOOK_CODE, TITLE, PRICE
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE AND P.PUBLISHER_NAME = 'Scribner' AND PRICE >= 14;

-- All Books In Stock In Branch 3
SELECT B.BOOK_CODE, TITLE, ON_HAND
FROM BOOK B, INVENTORY I
WHERE B.BOOK_CODE = I.BOOK_CODE AND BRANCH_NUM = 3;

-- All Books Published By "Berkley Publishing" With Type "PSY"
SELECT TITLE, TYPE, P.PUBLISHER_NAME
FROM BOOK B, PUBLISHER P
WHERE B.PUBLISHER_CODE = P.PUBLISHER_CODE AND TYPE = 'PSY' AND P.PUBLISHER_NAME = 'Berkley Publishing';

-- All Books By "Author 18"
SELECT TITLE
FROM BOOK
WHERE BOOK_CODE IN (SELECT BOOK_CODE FROM WROTE WHERE AUTHOR_NUM = 18);

-- All Books By "Author 18" But Using Exists
SELECT TITLE
FROM BOOK
WHERE EXISTS (SELECT BOOK_CODE FROM WROTE W WHERE BOOK.BOOK_CODE = W.BOOK_CODE AND AUTHOR_NUM = 18);

-- Books By "Author 20" In Branch 2
SELECT BOOK_CODE, TITLE
FROM BOOK
WHERE BOOK_CODE IN 
(SELECT BOOK_CODE FROM WROTE WHERE AUTHOR_NUM = 20 AND BOOK_CODE IN (SELECT BOOK_CODE FROM INVENTORY WHERE BRANCH_NUM = 2));

-- All Books On Hand By Author Last In Branch 4
SELECT TITLE, A.AUTHOR_LAST, ON_HAND
FROM BOOK B, INVENTORY I, AUTHOR A, WROTE W
WHERE B.BOOK_CODE = I.BOOK_CODE AND A.AUTHOR_NUM = W.AUTHOR_NUM AND I.BOOK_CODE = W.BOOK_CODE AND BRANCH_NUM = 4;

-- All Paperback Books On Hand By Author Last In Branch 4
SELECT TITLE, A.AUTHOR_LAST, ON_HAND
FROM BOOK B, INVENTORY I, AUTHOR A, WROTE W
WHERE B.BOOK_CODE = I.BOOK_CODE AND A.AUTHOR_NUM = W.AUTHOR_NUM AND I.BOOK_CODE = W.BOOK_CODE AND BRANCH_NUM = 4 AND PAPERBACK = 'Y';

-- All Books Published In Boston OR That Cost More Than 10 Dollars
SELECT BOOK_CODE, TITLE
FROM BOOK
WHERE PRICE > 10 OR PUBLISHER_CODE IN (SELECT PUBLISHER_CODE FROM PUBLISHER WHERE CITY = 'Boston');

-- All Books Published In Boston That Cost More Than 10 Dollars
SELECT BOOK_CODE, TITLE
FROM BOOK
WHERE PRICE > 10 AND PUBLISHER_CODE IN (SELECT PUBLISHER_CODE FROM PUBLISHER WHERE CITY = 'Boston');

-- All Books Not Published In Boston That Cost More Than 10 Dollars
SELECT BOOK_CODE, TITLE
FROM BOOK
WHERE PRICE > 10 AND PUBLISHER_CODE IN (SELECT PUBLISHER_CODE FROM PUBLISHER WHERE CITY != 'Boston');

-- All Books More Expensive Than All Books With Type "MYS"
SELECT BOOK_CODE, TITLE
FROM BOOK
WHERE PRICE > ALL (SELECT PRICE FROM BOOK WHERE TYPE = 'MYS');

-- All Books More Expensive Than At Least One Book With Type "MYS"
SELECT BOOK_CODE, TITLE
FROM BOOK
WHERE PRICE > ANY (SELECT PRICE FROM BOOK WHERE TYPE = 'MYS');

-- All Books In Stock Or Not In Branch 2
SELECT B.BOOK_CODE, TITLE, I.ON_HAND
FROM BOOK B
LEFT JOIN INVENTORY I ON B.BOOK_CODE = I.BOOK_CODE AND BRANCH_NUM = 2
ORDER BY BOOK_CODE;