--									Tables And Views With Alexamara Marina Group In SSMS

-- Load The Data Included In the "Database Creation For Analysis In SSMS" File Before Running The Below Commands.

-- Setting Database To Use
USE GUIDE;

-- Viewing All Alexamara Marina Group Tables
SELECT MARINA_NUM, NAME, ADDRESS, CITY, STATE, ZIP
FROM MARINA;

SELECT OWNER_NUM, LAST_NAME, FIRST_NAME, ADDRESS, CITY, STATE, ZIP
FROM OWNER;

SELECT SLIP_ID, MARINA_NUM, SLIP_NUM, LENGTH, FORMAT(RENTAL_FEE, 'C') AS RENTAL_FEE, BOAT_NAME, BOAT_TYPE, OWNER_NUM 
FROM MARINA_SLIP;

SELECT CATEGORY_NUM, CATEGORY_DESCRIPTION
FROM SERVICE_CATEGORY;

SELECT SERVICE_ID, SLIP_ID, CATEGORY_NUM, DESCRIPTION, STATUS, EST_HOURS, SPENT_HOURS, NEXT_SERVICE_DATE
FROM SERVICE_REQUEST;

-- Creating BOAT_SLIP Table
CREATE TABLE BOAT_SLIP
(SLIP_ID INT PRIMARY KEY NOT NULL,
MARINA_NUM CHAR(4),
SLIP_NUM VARCHAR(3),
LENGTH INT,
RENTAL_FEE INT,
BOAT_NAME VARCHAR(30),
BOAT_TYPE VARCHAR(30),
OWNER_NUM CHAR(4) );

-- Inserting Values Into BOAT_SLIP Table
INSERT INTO BOAT_SLIP VALUES
(12, '2', '7', 25, 1800, 'Bavant', 'Ray 25', 'FL13')

-- Viewing BOAT_SLIP Table
SELECT * FROM BOAT_SLIP;

-- Dropping BOAT_SLIP Table
DROP TABLE BOAT_SLIP;

-- Creating Table LARGE_SLIP
CREATE TABLE LARGE_SLIP
(MARINA_NUM CHAR(4) NOT NULL,
SLIP_NUM CHAR(4) NOT NULL,
RENTAL_FEE DECIMAL(8,2),
BOAT_NAME CHAR(50),
OWNER_NUM CHAR(4),
PRIMARY KEY (MARINA_NUM, SLIP_NUM));

-- Inserting Values Into LARGE_SLIP Table
INSERT INTO LARGE_SLIP
SELECT MARINA_NUM, SLIP_NUM, RENTAL_FEE, BOAT_NAME, OWNER_NUM
FROM MARINA_SLIP
WHERE LENGTH = 40;

-- Updating Values In LARGE_SLIP
UPDATE LARGE_SLIP
SET RENTAL_FEE = RENTAL_FEE + 150;

UPDATE LARGE_SLIP
SET RENTAL_FEE = RENTAL_FEE * .99
WHERE RENTAL_FEE > 4000;

UPDATE LARGE_SLIP
SET BOAT_NAME = NULL
WHERE MARINA_NUM = '1' AND SLIP_NUM = 'A1';

-- Adding More Values To The LARGE_SLIP Table
INSERT INTO LARGE_SLIP VALUES
('1', 'A4', 3900, 'Bilmore', 'FE82'); 

-- Deleting Values From The LARGE_SLIP Table
DELETE LARGE_SLIP
WHERE OWNER_NUM = 'TR72';

-- Adding Column To LARGE_SLIP Table
ALTER TABLE LARGE_SLIP
ADD CHARTER CHAR(1)

-- Adding And Changing Values To New Column
UPDATE LARGE_SLIP
SET CHARTER = 'N';

UPDATE LARGE_SLIP
SET CHARTER = 'Y'
WHERE BOAT_NAME = 'Our Toy';

-- Changing Format Of LARGE_SLIP Table Columns
ALTER TABLE LARGE_SLIP
ALTER COLUMN BOAT_NAME CHAR(60);

ALTER TABLE LARGE_SLIP
ALTER COLUMN RENTAL_FEE DECIMAL(8,2) NOT NULL;

-- Viewing Finished LARGE_SLIP Table
SELECT * FROM LARGE_SLIP;

-- Dropping LARGE_SLIP Table
DROP TABLE LARGE_SLIP;

-- Creating View LS
CREATE VIEW LS AS
SELECT MARINA_NUM, SLIP_NUM, RENTAL_FEE, BOAT_NAME, OWNER_NUM
FROM MARINA_SLIP
WHERE LENGTH = 40;

-- Which Boats Have A Rental Fee Greater Than 3000
SELECT * 
FROM LS 
WHERE RENTAL_FEE > 3800;

-- Creating View RAY_4025
CREATE VIEW RAY_4025 AS
SELECT MARINA_NUM, SLIP_NUM, LENGTH, RENTAL_FEE, BOAT_NAME, OWNER_NUM
FROM MARINA_SLIP
WHERE BOAT_TYPE = 'Ray 4025';

-- Which Ray 4025 Boats Have Rental Fees Less Than 4000
SELECT * 
FROM RAY_4025 
WHERE RENTAL_FEE < 4000;

-- Creating View SLIP_FEES
CREATE VIEW SLIP_FEES AS
SELECT LENGTH, AVG(RENTAL_FEE) AS AVERAGE_FEE
FROM MARINA_SLIP
GROUP BY LENGTH;

-- Which Boats Have Average Fees Of Less Than 3500
SELECT * 
FROM SLIP_FEES 
WHERE AVERAGE_FEE < 3500;

-- Creating An Index For OWNER_NUM In The MARINA_SLIP Table
CREATE INDEX BOAT_INDEX1 ON MARINA_SLIP(OWNER_NUM);

-- Creating An Index For BOAT_NAME In The MARINA_SLIP Table
CREATE INDEX BOAT_INDEX2 ON MARINA_SLIP(BOAT_NAME);

-- Creating An Index For LENGTH AND BOAT_NAME In The MARINA_SLIP Table
CREATE INDEX BOAT_INDEX3 ON MARINA_SLIP(LENGTH DESC, BOAT_NAME);

-- Dropping The Index For LENGTH AND BOAT_NAME In The MARINA_SLIP Table
DROP INDEX MARINA_SLIP.BOAT_INDEX3;

-- Adding A Foreign Key To A Table
ALTER TABLE MARINA_SLIP
ADD FOREIGN KEY (OWNER_NUM) REFERENCES OWNER;

-- Setting Up A Data Validation Check
ALTER TABLE MARINA_SLIP
ADD CHECK (LENGTH IN ('25', '30', '40') );

-- Testing Data Validation Check
UPDATE MARINA_SLIP
SET LENGTH = '37';